name: UpdateWiki
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install sphinx
      run: |
        apt-get install python-sphinx

    - name: Generate html
      run: |
        make html
        ls -al build/html
